### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by GaryGSC** [BYUCS452S2021/Ufinance#1]
I'm interested in collaborating on this project. I also pitched [CreditCardRewardsTracker](https://github.com/BYUCS452S2021/CreditCardRewardsTracker), which also happens to be in the FinTech space.

I guess we can use this issue to track people's interest in this project, much like I'm doing over in my repo, [here](https://github.com/BYUCS452S2021/CreditCardRewardsTracker/issues/1).

**Comment by GaryGSC** [comment]
I'm happiest when working on backend stuff and tooling.

Most of my background is with Node.js and AWS, if you're interested in taking this project in that direction.

I guess this is data analysis, though, so maybe Python is more useful? My Python is passable.

**Comment by jack40tall** [comment]
I am also interested in contributing to this project because I think I'll learn a lot in addition to being able to lending skills to the project. I'm not a front-end or back-end master, but I am proficient in both and can help out on both sides. My current job has me using React and Node.js to access an SQL database using graphQL as a middleware Rest API which overlaps with the big-picture ideas in this class.

**Comment by lgvw3** [comment]
I'm interested in this project as well. My emphasis is data science, so I could be useful in the data analysis. I also work as a web developer and have recently been working on reactive web development with the spring framework. Using reactive tools would enable the massive volume of financial data needed to be more constantly updated. For my frontend skills, I'm pretty solid with vuejs, nuxtjs and the likes.
